[project]
name = "wjx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "openai>=1.97.1",
    "playwright>=1.54.0",
    "requests>=2.32.4",
]
